package scanner;

public enum TokenType 
{
	LEFTBRACKET, RIGHTBRACKET, LEFTCURLY, RIGHTCURLY, 
	COMMA, COLON, SEMICOLON, LEFTPAREN, RIGHTPAREN, 
	AND, OR, MULT, DIV, ADD, MINUS, EQUAL, LESSEQ, 
	GREATEQ, LESSER, GREATER, ASSIGN, NOTEQUAL, 
	DOUBLETICK, SINGLETICK, PERIOD, COMMENTS, MOD,
	NONTERM, EXIT, NULL, NONE
}
